Trying to makes types and lifetimes explicit.
```
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
   --> src/main.rs:128:62
    |
128 |                 .and_then(move |stream| handler(stream, self.gimme())),
```

`UpstreamTlsConnector` now owns the `SocketAddr` and `TlsConnector`, which
simplifies some things but it does not help with the core problem at hand.