Future's lifetime subset of Self's lifetime, still no dice.
```
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
   --> src/main.rs:130:62
    |
130 |                 .and_then(move |stream| handler(stream, self.gimme())),
    |                                                              ^^^^^
    |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 111:5...
   --> src/main.rs:111:5
    |
111 | /     fn call<'c>(&mut self, _uri: Uri) -> Self::Future {
112 | |         fn handler<'a: 'b, 'b, S>(
113 | |             stream: S,
114 | |             tls_cx: &'a tokio_tls::TlsConnector,
...   |
131 | |         )
132 | |     }
    | |_____^
note: ...so that reference does not outlive borrowed content
   --> src/main.rs:130:57
    |
130 |                 .and_then(move |stream| handler(stream, self.gimme())),
    |                                                         ^^^^
note: but, the lifetime must be valid for the lifetime `'b` as defined on the impl at 101:14...
   --> src/main.rs:101:14
    |
101 | impl<'a: 'b, 'b> hyper::service::Service<hyper::Uri> for UpstreamTlsConnector<'a, 'b> {
    |              ^^
note: ...so that the types are compatible
   --> src/main.rs:111:55
    |
111 |       fn call<'c>(&mut self, _uri: Uri) -> Self::Future {
    |  _______________________________________________________^
112 | |         fn handler<'a: 'b, 'b, S>(
113 | |             stream: S,
114 | |             tls_cx: &'a tokio_tls::TlsConnector,
...   |
131 | |         )
132 | |     }
    | |_____^
    = note: expected  `tower_service::Service<http::uri::Uri>`
               found  `tower_service::Service<http::uri::Uri>`
```